server:
    port: 8090
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/aaatest?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username : admin
    password : admin
    driverClassName : com.mysql.jdbc.Driver